services:
  backend:
    build: ./backend
    image: samudhyan-backend:latest
    container_name: samudhyan_backend
    ports:
      - "8000:8000"
    env_file: .env.dev
    restart: unless-stopped
    volumes:
      - ./backend:/app   